### ISSUE TITLE
[Todo] Optimization pt. 4 : pipelining

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#48]
@yorhel
> The API support pipelining, meaning you can send multiple
commands in one go, without waiting for the server to reply to the first
command. This can complicate your code a bit depending on how it's
structured, but on networks with a bit of a latency this should give a
*very* significant performance boost.

> Performance-wise, pipelining is pretty much equivalent to increasing to
increasing the max number of results per command.

**Comment by herbeth1u** [comment]
Deadlocks appear because there seems to be problems using the same input stream and the same output stream.
It is not possible to keep the same socket and clone the input stream and output stream.

Solution to test : 
- [ ] Create a socket per thread and connect to the API with each one.
- [ ] Beware of the "5 max connections per IP" limit.

**Comment by herbeth1u** [comment]
Strange error appears even in production when I play with my sockets : 

06-08 20:21:27.282 25325-25373/com.booboot.vndbandroid W/System.err: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
06-08 20:21:27.282 25325-25373/com.booboot.vndbandroid W/System.err:     at com.android.org.conscrypt.SSLNullSession.getPeerPrincipal(SSLNullSession.java:119)
06-08 20:21:27.282 25325-25373/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer.connect(VNDBServer.java:77)
06-08 20:21:27.282 25325-25373/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer.login(VNDBServer.java:99)
06-08 20:21:27.282 25325-25373/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.SocketPool.getSocket(SocketPool.java:22)
06-08 20:21:27.282 25325-25373/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer.sendCommand(VNDBServer.java:242)
06-08 20:21:27.282 25325-25373/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer$1.run(VNDBServer.java:164)
06-08 20:21:27.284 25325-25374/com.booboot.vndbandroid W/System.err: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
06-08 20:21:27.284 25325-25374/com.booboot.vndbandroid W/System.err:     at com.android.org.conscrypt.SSLNullSession.getPeerPrincipal(SSLNullSession.java:119)
06-08 20:21:27.284 25325-25374/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer.connect(VNDBServer.java:77)
06-08 20:21:27.284 25325-25374/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer.login(VNDBServer.java:99)
06-08 20:21:27.284 25325-25374/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.SocketPool.getSocket(SocketPool.java:22)
06-08 20:21:27.285 25325-25374/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer.sendCommand(VNDBServer.java:242)
06-08 20:21:27.285 25325-25374/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer$1.run(VNDBServer.java:164)
06-08 20:21:27.285 25325-25379/com.booboot.vndbandroid W/System.err: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
06-08 20:21:27.285 25325-25379/com.booboot.vndbandroid W/System.err:     at com.android.org.conscrypt.SSLNullSession.getPeerPrincipal(SSLNullSession.java:119)
06-08 20:21:27.286 25325-25379/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer.connect(VNDBServer.java:77)
06-08 20:21:27.286 25325-25379/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer.login(VNDBServer.java:99)
06-08 20:21:27.286 25325-25379/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.SocketPool.getSocket(SocketPool.java:22)
06-08 20:21:27.286 25325-25379/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer.sendCommand(VNDBServer.java:242)
06-08 20:21:27.286 25325-25379/com.booboot.vndbandroid W/System.err:     at com.booboot.vndbandroid.api.VNDBServer$1.run(VNDBServer.java:164)

**Comment by herbeth1u** [comment]
The SSL exception raises when the server rejected the socket because of the 5-socket limit.
So it would mean that we're trying to bind another socket while the previous one wasn't properly closed.

**Comment by herbeth1u** [comment]
Using socket.setKeepAlive(false), the behavior is fine and the problem seems solved.
Keep monitoring for side effects.

**Comment by herbeth1u** [comment]
Nothing weird to report since last commit. Closing issue.
