### ISSUE TITLE
[Bug] SQLite duplicate primary keys

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#65]
Similar novels are inserted in duplicate.
**SOLUTION** : PK of SIMILAR_NOVELS should be (id, vn) and not just (id) since it's an association table!

```
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: similar_novels.id (code 1555)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:732)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1676)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
        at com.booboot.vndbandroid.api.DB.saveSimilarNovels(DB.java:871)
        at com.booboot.vndbandroid.activity.VNDetailsActivity$4$4.config(VNDetailsActivity.java:496)
        at com.booboot.vndbandroid.util.Callback$1.run(Callback.java:32)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by herbeth1u** [comment]
Idea for the future (optimization) : Try "INSERT OR IGNORE" clause (instead of SELECT + INSERT if) to avoid duplicates.
