### ISSUE TITLE
[Bug] VN == null in VNDetailsActivity.onCreate() 

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#80]
Build version: 2.0.2 
Build date: 1979-11-30 00:00:00 
Current date: 2016-10-14 22:57:02 
Device: TURKCELL T60 
Android version: 5.0.2

Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.booboot.vndbandroid/com.booboot.vndbandroid.activity.VNDetailsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.booboot.vndbandroid.bean.vndb.Item.getId()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2357)
    at android.app.ActivityThread.access$800(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5218)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.booboot.vndbandroid.bean.vndb.Item.getId()' on a null object reference
    at com.booboot.vndbandroid.activity.VNDetailsActivity.init(VNDetailsActivity.java:129)
    at com.booboot.vndbandroid.activity.VNDetailsActivity.onCreate(VNDetailsActivity.java:125)
    at android.app.Activity.performCreate(Activity.java:5976)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
    ... 10 more

**Comment by herbeth1u** [comment]
The problem still persists! 
I've found another trigger though : going to a VN page, removing it from all one's lists then flipping the device.

**Comment by herbeth1u** [comment]
Still happens, even though more rarely!

**Comment by herbeth1u** [comment]
Investigate relation to this bug:

```
Build version: 2.0.9 
Build date: 1979-11-30 00:00:00 
Current date: 2016-11-29 22:31:24 
Device: OnePlus ONEPLUS A3000 
Android version: 6.0.1
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.booboot.vndbandroid/com.booboot.vndbandroid.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.booboot.vndbandroid.bean.vndb.Item.getTitle()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2456)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
	at android.app.ActivityThread.access$900(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5507)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.booboot.vndbandroid.bean.vndb.Item.getTitle()' on a null object reference
	at com.booboot.vndbandroid.factory.VNCardFactory.buildCard(VNCardFactory.java:27)
	at com.booboot.vndbandroid.factory.ProgressiveResultLoader.initFromExisting(ProgressiveResultLoader.java:153)
	at com.booboot.vndbandroid.activity.ranking.RankingMostVotedFragment.onCreateView(RankingMostVotedFragment.java:35)
	at android.app.Fragment.performCreateView(Fragment.java:2220)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	at android.app.BackStackRecord.run(BackStackRecord.java:793)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1540)
	at android.app.FragmentController.execPendingActions(FragmentController.java:325)
	at android.app.Activity.performStart(Activity.java:6327)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
	... 10 more
```

Something is VERY fishy in VNDBServer.sendCommand:283. That call to Cache.loadFromCache probably shouldn't be here. It resets Cache.vns to the content of the database, though it's a very bad idea to do it once the log in phase is done! Probably some old code from the early stages of the app when the cache wasn't systematically initialized at startup.
( Also, since that code executes only when SocketException occurs, that would explain why it's rare and why I can never seem to reproduce this bug, since I always test and develop from home with a stable connection... )

**Comment by herbeth1u** [comment]
Rest of the story in #97
