### ISSUE TITLE
[Bug] Unable to start activity 

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#97]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.booboot.vndbandroid/com.booboot.vndbandroid.activity.VNDetailsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.booboot.vndbandroid.bean.vndb.Item.getId()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2381)
	at android.app.ActivityThread.access$800(ActivityThread.java:147)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5260)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.booboot.vndbandroid.bean.vndb.Item.getId()' on a null object reference
	at com.booboot.vndbandroid.activity.VNDetailsActivity.init(VNDetailsActivity.java:143)
	at com.booboot.vndbandroid.activity.VNDetailsActivity.onCreate(VNDetailsActivity.java:136)
	at android.app.Activity.performCreate(Activity.java:5975)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2274)
	... 10 more
```

I haven't ever managed to reproduce this bug but it seems quite frequent and happens only after an activity restart, when spoilerLevel > 0 (so after modifying the spoiler level).
The activity's extras don't seem to be recreated under some specific and unknown circumstances, on specific and unknown devices...

- [x] Add VN_ID in onSaveInstanceState() and retrieve in onCreate() if the extra is null.

**Comment by herbeth1u** [comment]
http://stackoverflow.com/questions/10371789/losing-intent-extras-when-returning-to-activity

**Comment by herbeth1u** [comment]
The error is still happening and now I have no fucking idea why. I'll just assume it's Android or the OEM making an absolute mess of my variables because there's no way the problem's in my code anymore. 

That being said I should ask the people victim of this bug to tell me exactly what they were doing.

**Comment by herbeth1u** [comment]
Finally found the root cause of the problem! 

When heavy apps are running on the device (like a game basically), Android is releasing resources in VNDBA to make space in the RAM for the game. When I get back to the app, Android has destroyed my static variables but still tries to recreate the same activity (instead of restarting the whole app)! Hence the crash. Though I read that it is supposed to happen, it is definitely fucking happening. 
The same goes for the ranking pages. 

Solution : if Cache.vns is empty and not empty account, then :
- Easy one :  restart app and finish() the current activity 
- Hard one : reload cache and try to resume with the current activity

**Comment by herbeth1u** [comment]
Put the fix in every activity because it can mess up any activity (without necessarily crashing).

**Comment by herbeth1u** [comment]
Steps to reproducing the problem:
- _Developer options_ > _Background process limit_ > _No background process_
- Start app, open a VN
- Go back to the Settings app
- Go back to VNDBA.

**Comment by herbeth1u** [comment]
The new fix is more elegant and seems to work fine. Tested with the test account, on MainActivity, VNDetailsActivity (with or without 'get vn' callback) and VNSearchActivity.
Still need to test it on fragments (especially the rankings which crashed).
